// <auto-generated />
using BoniboNews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoniboNews.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20231110161400_updates")]
    partial class updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoniboNews.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "ندارد",
                            CreateDate = "1402 / 08 / 19",
                            Description = "بونیبو ، در مدرسه به آموزش میده ، ما با بونیبو سرگرمی خواصخودمون رو داریم",
                            ItemName = "سعید بونیبو در مدرسه",
                            ViewCount = 1
                        },
                        new
                        {
                            Id = 2,
                            Comments = "ندارد",
                            CreateDate = "1402 / 08 / 19",
                            Description = "هیچی ، فقط یس بونیبو",
                            ItemName = "یس بونیبو",
                            ViewCount = 1
                        },
                        new
                        {
                            Id = 3,
                            Comments = "ندارد",
                            CreateDate = "1402 / 08 / 19",
                            Description = "این محصول بخاطر علاقه شدید بونیبو وارد شده ، آدرس جهت خرید : جنب مذرسه شریعتی هایپرمارکت ماهان",
                            ItemName = "گل محمدی",
                            ViewCount = 1
                        });
                });

            modelBuilder.Entity("BoniboNews.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
